[build]
  system_packages = ["python3", "python3-pip", "python3-venv"]
  build_cmd = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
  start_cmd = "bash start.sh"
