[phases.setup]
nixPkgs = ["portaudio", "alsa-lib", "ffmpeg"]

[phases.build]
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "streamlit run meeting_main.py --server.port=8501 --server.address=0.0.0.0"


